import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Product",
  description: "Generated by create next app",
};

function Products<T>() {
  return <div>123</div>;
}

export default Products;
